version: '2'
services:
 oauth2server:
  image: psd2/oauth2server
  ports:
   - "8081:8081"
  volumes:
   - /logs:/logs
  env_file: .env
 
 psd2api:
  image: psd2/psd2api
  ports:
   - "8082:8082"
  volumes:
   - /logs:/logs
  env_file: .env
  depends_on:
  - oauth2server

